default-world: Waiting
status-secret: ''
voting-url: ''
maps:
- name: creative
  width: 3
- name: survival
  width: 3
- name: build
  width: 3
worlds:
- name: Unsupported version
  folder: unsupported
  spawn: 0.5,32,0.5,180,0
  environment:
    time: 18000
  bounds:
    pos1: 16,255,16
    pos2: -16,0,-16
  portals: {}
- name: Waiting
  folder: waiting
  spawn: 0,32,0,180,0
  environment:
    time: 18000
  bounds:
    pos1: 111,255,111
    pos2: -95,0,-95
  portals:
    - pos1: -5,30,-13
      pos2: -3,31,-11
      server: creative
    - pos1: -1,30,-13
      pos2: 1,31,-11
      server: survival
    - pos1: 3,30,-13
      pos2: 5,31,-11
      server: build
  maps:
    - name: creative
      direction: north
      pos: -3,35,-12
    - name: creative
      direction: south
      pos: -5,35,-12
    - name: survival
      direction: north
      pos: 1,35,-12
    - name: survival
      direction: south
      pos: -1,35,-12
    - name: build
      direction: north
      pos: 5,35,-12
    - name: build
      direction: south
      pos: 3,35,-12
  status-holograms:
    - server: creative
      pos: -4,33.5,-11
    - server: survival
      pos: 0,34,-11
    - server: build
      pos: 4,33.5,-11
- name: Waiting Winter
  folder: waiting_winter
  spawn: 0,32,0,180,0
  environment:
    time: 18000
    weather: 'rain'
  bounds:
    pos1: 111,255,111
    pos2: -95,0,-95
  portals:
    - pos1: -5,30,-14
      pos2: -3,31,-12
      server: creative
    - pos1: -1,30,-14
      pos2: 1,31,-12
      server: survival
    - pos1: 3,30,-14
      pos2: 5,31,-12
      server: build



