default-world: 'The Hidden Castle'
status-secret: ''
voting-url: ''
maps:
- name: creative
  width: 3
- name: stresstest
  width: 3
- name: survival
  width: 3
- name: build
  width: 3
worlds:
- name: Waiting
  folder: waiting
  spawn: 0,32,0,180,0
  environment:
    time: 18000
  bounds:
    pos1: 111,255,111
    pos2: -95,0,-95
  portals:
    - pos1: -5,30,-13
      pos2: -3,31,-11
      server: creative
    - pos1: -1,30,-13
      pos2: 1,31,-11
      server: stresstest
    - pos1: 3,30,-13
      pos2: 5,31,-11
      server: build
  maps:
    - name: creative
      direction: north
      pos: -3,35,-12
    - name: creative
      direction: south
      pos: -5,35,-12
    - name: stresstest
      direction: north
      pos: 1,35,-12
    - name: stresstest
      direction: south
      pos: -1,35,-12
    - name: build
      direction: north
      pos: 5,35,-12
    - name: build
      direction: south
      pos: 3,35,-12
  status-holograms:
    - server: creative
      pos: -4,33.5,-11
    - server: stresstest
      pos: 0,34,-11
    - server: build
      pos: 4,33.5,-11
- name: Harristown Forest
  contributors:
    - Jimbus Khan
    - _ColdDestroy_
    - ICommitTaxEvade
    - Aerrro
    - TicTacTin
    - Personman6000
  folder: entry14
  spawn: 8,33,-5,0,0
  environment:
    time: 23200
  bounds:
    pos1: 79,255,79
    pos2: -64,0,-64
  portals:
    - pos1: 11,32,7
      pos2: 13,32,9
      server: creative
    - pos1: 7,32,7
      pos2: 9,32,9
      server: stresstest
    - pos1: 3,32,7
      pos2: 5,32,9
      server: build
  maps:
    - name: creative
      direction: north
      pos: 13,36,8
    - name: creative
      direction: south
      pos: 11,36,8
    - name: creative
      direction: bottom
      pos: 11,32,8
    - name: stresstest
      direction: north
      pos: 9,36,8
    - name: stresstest
      direction: south
      pos: 7,36,8
    - name: stresstest
      direction: bottom
      pos: 7,32,8
    - name: build
      direction: north
      pos: 5,36,8
    - name: build
      direction: south
      pos: 3,36,8
    - name: build
      direction: bottom
      pos: 3,32,8
  status-holograms:
    - server: creative
      pos: 12,34.5,7
    - server: stresstest
      pos: 8,35,7
    - server: build
      pos: 4,34.5,7
- name: RTManor
  contributors:
    - Senor_Kevin
  folder: entry6
  spawn: -22,35,-64,0,0
  environment:
    time: 3853
  bounds:
    pos1: 79,255,79
    pos2: -64,0,-64
  portals:
    - pos1: -19,35,-57
      pos2: -17,35,-55
      server: creative
    - pos1: -23,35,-57
      pos2: -21,35,-55
      server: stresstest
    - pos1: -27,35,-57
      pos2: -25,35,-55
      server: build
  maps:
    - name: creative
      direction: north
      pos: -17,40,-56
    - name: creative
      direction: south
      pos: -19,40,-56
    - name: stresstest
      direction: north
      pos: -21,40,-56
    - name: stresstest
      direction: south
      pos: -23,40,-56
    - name: build
      direction: north
      pos: -25,40,-56
    - name: build
      direction: south
      pos: -27,40,-56
  status-holograms:
    - server: creative
      pos: -18,37.5,-57
    - server: stresstest
      pos: -22,38,-57
    - server: build
      pos: -26,37.5,-57
- name: CrispFriedHannah's Entry
  contributors:
    - CrispFriedHannah
  folder: entry24
  spawn: 8,33,-2,0,0
  environment:
    time: 3853
    #music: 'minecraft:music_disc.cat'
    weather: rain
  bounds:
    pos1: 79,255,79
    pos2: -64,0,-64
  portals:
    - pos1: 11,32,7
      pos2: 13,32,9
      server: creative
    - pos1: 7,32,7
      pos2: 9,32,9
      server: stresstest
    - pos1: 3,32,7
      pos2: 5,32,9
      server: build
  maps:
    - name: creative
      direction: north
      pos: 13,36,8
    - name: creative
      direction: south
      pos: 11,36,8
    - name: stresstest
      direction: north
      pos: 9,36,8
    - name: stresstest
      direction: south
      pos: 7,36,8
    - name: build
      direction: north
      pos: 5,36,8
    - name: build
      direction: south
      pos: 3,36,8
  status-holograms:
    - server: creative
      pos: 12,34.5,7
    - server: stresstest
      pos: 8,35,7
    - server: build
      pos: 4,34.5,7
- name: Library
  contributors:
    - Tklots
  folder: entry11
  spawn: 9,33,-4,0,0
  environment:
    dimension: the_end
    time: 2400
    #music: 'minecraft:music_disc.mall'
  bounds:
    pos1: 79,255,79
    pos2: -64,0,-64
  portals:
    - pos1: 15,33,9
      pos2: 17,36,9
      server: creative
    - pos1: 8,33,9
      pos2: 10,36,9
      server: stresstest
    - pos1: 1,33,9
      pos2: 3,36,9
      server: build
  maps:
    - name: creative
      direction: north
      pos: 17,37,9
    - name: stresstest
      direction: north
      pos: 10,37,9
    - name: build
      direction: north
      pos: 3,37,9
  status-holograms:
    - server: creative
      pos: 16,35,8
    - server: stresstest
      pos: 9,35,8
    - server: build
      pos: 2,35,8
- name: RTGalaxTree
  contributors:
    - _Cynder_
    - ValentinT
    - Tklots
    - WhimsyBridges
    - LonkReborn
  folder: entry35
  spawn: 39,66,-9,90,0
  environment:
    time: 13500
  bounds:
    pos1: 79,255,79
    pos2: -64,0,-64
  portals:
    - pos1: 32,66,-4
      pos2: 32,70,-2
      server: creative
    - pos1: 32,66,-10
      pos2: 32,70,-8
      server: stresstest
    - pos1: 32,66,-16
      pos2: 32,70,-14
      server: build
  maps:
    - name: creative
      direction: east
      pos: 32,71,-2
    - name: stresstest
      direction: east
      pos: 32,71,-8
    - name: build
      direction: east
      pos: 32,71,-14
  status-holograms:
    - server: creative
      pos: 34,68,-3
    - server: stresstest
      pos: 34,68,-9
    - server: build
      pos: 34,68,-15
- name: Oasis
  contributors:
    - LadanTF2
  folder: entry3
  spawn: 8,34,5,0,0
  environment:
    time: 3853
  bounds:
    pos1: 79,255,79
    pos2: -64,0,-64
  portals:
    - pos1: 11,32,17
      pos2: 13,32,19
      server: creative
    - pos1: 7,32,17
      pos2: 9,32,19
      server: stresstest
    - pos1: 3,32,17
      pos2: 5,32,19
      server: build
  maps:
    - name: creative
      direction: north
      pos: 13,36,18
    - name: creative
      direction: south
      pos: 11,36,18
    - name: stresstest
      direction: north
      pos: 9,36,18
    - name: stresstest
      direction: south
      pos: 7,36,18
    - name: build
      direction: north
      pos: 5,36,18
    - name: build
      direction: south
      pos: 3,36,18
  status-holograms:
    - server: creative
      pos: 12,34.5,17
    - server: stresstest
      pos: 8,34.5,17
    - server: build
      pos: 4,34.5,17
- name: '1952'
  contributors:
    - YourLocalPiebro
  folder: entry4
  spawn: 47,34,22,180,0
  environment:
    time: 18000
  bounds:
    pos1: 79,255,79
    pos2: -64,0,-64
  portals:
    - pos1: 42,33,7
      pos2: 44,33,9
      server: creative
    - pos1: 46,33,7
      pos2: 48,33,9
      server: stresstest
    - pos1: 50,33,7
      pos2: 52,33,9
      server: build
  maps:
    - name: creative
      direction: north
      pos: 44,37,8
    - name: creative
      direction: south
      pos: 42,37,8
    - name: stresstest
      direction: north
      pos: 48,37,8
    - name: stresstest
      direction: south
      pos: 46,37,8
    - name: build
      direction: north
      pos: 52,37,8
    - name: build
      direction: south
      pos: 50,37,8
  status-holograms:
    - server: creative
      pos: 43,35.5,9
    - server: stresstest
      pos: 47,36,9
    - server: build
      pos: 51,35.5,9
- name: The Grand Library
  contributors:
    - WhimsyBridges
    - LonkReborn
  folder: entry30
  spawn: -6,74,30,180,0
  environment:
    time: 3853
  bounds:
    pos1: 79,255,79
    pos2: -64,0,-64
  portals:
    - pos1: -11,73,17
      pos2: -9,73,19
      server: creative
    - pos1: -7,73,17
      pos2: -5,73,19
      server: stresstest
    - pos1: -3,73,17
      pos2: -1,73,19
      server: build
  maps:
    - name: creative
      direction: north
      pos: -9,77,18
    - name: creative
      direction: south
      pos: -11,77,18
    - name: stresstest
      direction: north
      pos: -5,77,18
    - name: stresstest
      direction: south
      pos: -7,77,18
    - name: build
      direction: north
      pos: -1,77,18
    - name: build
      direction: south
      pos: -3,77,18
  status-holograms:
    - server: creative
      pos: -10,75.5,19
    - server: stresstest
      pos: -6,76,19
    - server: build
      pos: -2,75.5,19
- name: Lush Caves
  contributors:
    - +periuwu5882
  folder: entry9
  spawn: 8,33,-5,0,0
  environment:
    time: 3853
    music: 'minecraft:music_disc.otherside'
  bounds:
    pos1: 79,255,79
    pos2: -64,0,-64
  portals:
    - pos1: 11,32,7
      pos2: 13,32,9
      server: creative
    - pos1: 7,32,7
      pos2: 9,32,9
      server: stresstest
    - pos1: 3,32,7
      pos2: 5,32,9
      server: build
  maps:
    - name: creative
      direction: north
      pos: 13,36,8
    - name: stresstest
      direction: north
      pos: 9,36,8
    - name: build
      direction: north
      pos: 5,36,8
  status-holograms:
    - server: creative
      pos: 12,34.5,7
    - server: stresstest
      pos: 8,35,7
    - server: build
      pos: 4,34.5,7
- name: Sakura Gardens
  contributors:
    - CrispyMiner
  folder: entry19
  spawn: 21,34,18,180,0
  environment:
    time: 22500
    #music: 'minecraft:music_disc.mall'
  bounds:
    pos1: 79,255,79
    pos2: -64,0,-64
  portals:
    - pos1: 14,33,10
      pos2: 16,33,12
      server: creative
    - pos1: 20,33,10
      pos2: 22,33,12
      server: stresstest
    - pos1: 26,33,10
      pos2: 28,33,12
      server: build
  maps:
    - name: creative
      direction: south
      pos: 14,37,12
    - name: stresstest
      direction: south
      pos: 20,37,12
    - name: build
      direction: south
      pos: 26,37,12
  status-holograms:
    - server: creative
      pos: 15,35.5,13
    - server: stresstest
      pos: 21,36,13
    - server: build
      pos: 27,35.5,13
- name: Portal Forest
  contributors:
    - PrinceTrellis
  folder: entry22
  spawn: 8,33,-5,0,0
  environment:
    time: 13500
  bounds:
    pos1: 79,255,79
    pos2: -64,0,-64
  portals:
    - pos1: 13,33,8
      pos2: 15,38,8
      server: creative
    - pos1: 7,33,8
      pos2: 9,38,8
      server: stresstest
    - pos1: 1,33,8
      pos2: 3,38,8
      server: build
  maps:
    - name: creative
      direction: north
      pos: 15,38,7
    - name: stresstest
      direction: north
      pos: 9,38,7
    - name: build
      direction: north
      pos: 3,38,7
  status-holograms:
    - server: creative
      pos: 14,35,5
    - server: stresstest
      pos: 8,35,5
    - server: build
      pos: 2,35,5
- name: The Hidden Castle
  contributors:
    - Lord_Primordius
    - KEVON13579
    - Andrew1355
    - jamesmarkwaller
    - Oa6ix
    - Badwolfe44
  folder: entry21
  spawn: 8,33,-2,0,0
  environment:
    time: 2000
  bounds:
    pos1: 79,255,79
    pos2: -64,0,-64
  portals:
    - pos1: 11,32,3
      pos2: 13,32,5
      server: creative
    - pos1: 7,32,7
      pos2: 9,32,9
      server: stresstest
    - pos1: 3,32,3
      pos2: 5,32,5
      server: build
  maps:
    - name: creative
      direction: north
      pos: 15,37,6
    - name: stresstest
      direction: north
      pos: 9,38,10
    - name: build
      direction: north
      pos: 3,36,6
  status-holograms:
    - server: creative
      pos: 12,34.5,4
    - server: stresstest
      pos: 8,35,8
    - server: build
      pos: 4,34.5,4