default-world: Waiting
tablist-text: |-
  \u00a7aWelcome to the RTGame Minecraft Hub!
  \u00a79Walk through a portal to join a server
  \u00a79
worlds:
- name: Waiting
  folder: waiting
  spawn: -21,33,8,-90,0
  environment:
    time: 1000
  bounds:
    pos1: 62,255,78
    pos2: -78,0,-62
  portals:
    - pos1: -8,36,3
      pos2: -8,33,5
      server: creative
    - pos1: -8,36,7
      pos2: -8,33,9
      server: survival
    - pos1: -8,36,11
      pos2: -8,33,13
      server: build
- name: Waiting 1.16.2
  folder: waiting2
  spawn: -21,33,8,-90,0
  environment:
    time: 18000
  bounds:
    pos1: 62,255,78
    pos2: -78,0,-62
  portals:
    - pos1: -9,31,3
      pos2: -7,31,5
      server: creative
    - pos1: -9,31,7
      pos2: -7,31,9
      server: survival
    - pos1: -9,31,11
      pos2: -7,31,13
      server: build
- name: Anniversary
  folder: anniversary
  spawn: -21,33,8,-90,0
  environment:
    time: 18000
  bounds:
    pos1: 62,255,78
    pos2: -78,0,-62
  portals:
    - pos1: -8,36,3
      pos2: -8,33,5
      server: creative
    - pos1: -8,36,7
      pos2: -8,33,9
      server: survival
    - pos1: -8,36,11
      pos2: -8,33,13
      server: build



