default-world: Harristown Forest
status-secret: ''
voting-url: ''
maps:
- name: creative
  width: 3
- name: survival
  width: 3
- name: build
  width: 3
worlds:
- name: Unsupported version
  folder: unsupported
  spawn: 0.5,32,0.5,180,0
  environment:
    time: 18000
  bounds:
    pos1: 16,255,16
    pos2: -16,0,-16
  portals: {}
- name: Waiting
  folder: waiting
  spawn: 0,32,0,180,0
  environment:
    time: 18000
  bounds:
    pos1: 111,255,111
    pos2: -95,0,-95
  portals:
    - pos1: -5,30,-13
      pos2: -3,31,-11
      server: creative
    - pos1: -1,30,-13
      pos2: 1,31,-11
      server: survival
    - pos1: 3,30,-13
      pos2: 5,31,-11
      server: build
  maps:
    - name: creative
      direction: north
      pos: -3,35,-12
    - name: creative
      direction: south
      pos: -5,35,-12
    - name: survival
      direction: north
      pos: 1,35,-12
    - name: survival
      direction: south
      pos: -1,35,-12
    - name: build
      direction: north
      pos: 5,35,-12
    - name: build
      direction: south
      pos: 3,35,-12
  status-holograms:
    - server: creative
      pos: -4,33.5,-11
    - server: survival
      pos: 0,34,-11
    - server: build
      pos: 4,33.5,-11
- name: Waiting Winter
  folder: waiting_winter
  spawn: 0,32,0,180,0
  environment:
    time: 18000
    weather: 'rain'
  bounds:
    pos1: 111,255,111
    pos2: -95,0,-95
  portals:
    - pos1: -5,30,-14
      pos2: -3,31,-12
      server: creative
    - pos1: -1,30,-14
      pos2: 1,31,-12
      server: survival
    - pos1: 3,30,-14
      pos2: 5,31,-12
      server: build
- name: Harristown Forest
  contributors:
    - Jimbus Khan
    - _ColdDestroy_
    - ICommitTaxEvade
    - Aerrro
    - TicTacTin
    - Personman6000
  folder: entry14
  spawn: 8,33,-5,0,0
  environment:
    time: 23200
  bounds:
    pos1: 79,255,79
    pos2: -64,0,-64
  portals:
    - pos1: 11,32,7
      pos2: 13,32,9
      server: creative
    - pos1: 7,32,7
      pos2: 9,32,9
      server: survival
    - pos1: 3,32,7
      pos2: 5,32,9
      server: build
  maps:
    - name: creative
      direction: north
      pos: 13,36,8
    - name: creative
      direction: south
      pos: 11,36,8
    - name: creative
      direction: bottom
      pos: 11,32,8
    - name: survival
      direction: north
      pos: 9,36,8
    - name: survival
      direction: south
      pos: 7,36,8
    - name: survival
      direction: bottom
      pos: 7,32,8
    - name: build
      direction: north
      pos: 5,36,8
    - name: build
      direction: south
      pos: 3,36,8
    - name: build
      direction: bottom
      pos: 3,32,8
  status-holograms:
    - server: creative
      pos: 12,34.5,7
    - server: survival
      pos: 8,35,7
    - server: build
      pos: 4,34.5,7

