default-world: Waiting Winter
tablist-text: |-
  \u00a7aWelcome to the RTGame Minecraft Hub!
  \u00a79Walk through a portal to join a server
  \u00a79
worlds:
- name: Waiting 1.15
  folder: waiting_old
  spawn: -21,33,8,-90,0
  environment:
    time: 18000
  bounds:
    pos1: 62,255,78
    pos2: -78,0,-62
  portals:
    - pos1: -8,36,3
      pos2: -8,33,5
      server: creative
    - pos1: -8,36,7
      pos2: -8,33,9
      server: survival
    - pos1: -8,36,11
      pos2: -8,33,13
      server: build
- name: Waiting 1.16.2
  folder: waiting
  spawn: 0,32,0,180,0
  environment:
    time: 18000
  bounds:
    pos1: 111,255,111
    pos2: -95,0,-95
  portals:
    - pos1: -5,30,-14
      pos2: -3,31,-12
      server: creative
    - pos1: -1,30,-14
      pos2: 1,31,-12
      server: survival
    - pos1: 3,30,-14
      pos2: 5,31,-12
      server: build
- name: Waiting Winter
  folder: waiting_winter
  spawn: 0,32,0,180,0
  environment:
    time: 18000
    weather: 'rain'
  bounds:
    pos1: 111,255,111
    pos2: -95,0,-95
  portals:
    - pos1: -5,30,-14
      pos2: -3,31,-12
      server: creative
    - pos1: -1,30,-14
      pos2: 1,31,-12
      server: survival
    - pos1: 3,30,-14
      pos2: 5,31,-12
      server: build
- name: Anniversary
  folder: anniversary
  spawn: -21,33,8,-90,0
  environment:
    time: 18000
  bounds:
    pos1: 62,255,78
    pos2: -78,0,-62
  portals:
    - pos1: -8,36,3
      pos2: -8,33,5
      server: creative
    - pos1: -8,36,7
      pos2: -8,33,9
      server: survival
    - pos1: -8,36,11
      pos2: -8,33,13
      server: build



