name: Package Application with Pyinstaller

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Package Application
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.8'
        spec: 'waitingserver/server.spec'
        requirements: 'waitingserver/requirements.txt'
        
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: WaitingServer/dist/server
        target: server

    - name: Tar packets
      run: tar -cvf packets.tar packets

    - uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        name: waitingserver-linux
        path: |
          server
          packets.tar
          maps
          config.yml
        
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Package Application
      uses: sayyid5416/pyinstaller@v1
      with:
        path: waitingserver
        python_ver: '3.8'
        spec: 'waitingserver/server.spec'
        requirements: 'waitingserver/requirements.txt'
        
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: WaitingServer/dist/server.exe
        target: server.exe

    - name: Tar packets
      run: tar -cvf packets.tar packets

    - uses: actions/upload-artifact@v3
      with:
        if-no-files-found: error
        name: waitingserver-windows
        path: |
          server.exe
          packets.tar
          maps
          config.yml
