name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: waitingserver

    - uses: actions/upload-artifact@v2
      with:
        name: waitingserver
        path: waitingserver/dist/linux
        
  build-windows:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: waitingserver

    - uses: actions/upload-artifact@v2
      with:
        name: waitingserver.exe
        path: waitingserver/dist/windows
